'use strict';
function firDesign(M,fc,fs){let b=Array.from({length:M},(_,n)=>{let k=n-(M-1)/2;return (k===0?2*fc/fs:Math.sin(2*Math.PI*fc/fs*k)/(Math.PI*k))*(.54-.46*Math.cos(2*Math.PI*n/(M-1)));});const sum=b.reduce((a,v)=>a+v,0);return b.map(v=>v/sum);}
function butterDesign(N,fc,fs){const w=2*Math.PI*fc/fs,c=Math.cos(w);return Array.from({length:N/2},(_,k)=>{const Q=1/(2*Math.cos((2*k+1)*Math.PI/(2*N))),alpha=Math.sin(w)/(2*Q),a0=1+alpha;return {b:[(1-c)/2/a0,(1-c)/a0,(1-c)/2/a0],a:[1,-2*c/a0,(1-alpha)/a0],Q};});}
function polynomial(c,w){return c.reduce((s,v,n)=>({re:s.re+v*Math.cos(w*n),im:s.im-v*Math.sin(w*n)}),{re:0,im:0});}
function magnitude(b,a,f,fs){const n=polynomial(b,2*Math.PI*f/fs),d=polynomial(a,2*Math.PI*f/fs);return Math.hypot(n.re,n.im)/Math.hypot(d.re,d.im);}
function kalmanStep(s,z,dt,q,R){const xp=s.x[0]+dt*s.x[1],vp=s.x[1],A=s.P[0]+2*dt*s.P[1]+dt*dt*s.P[3]+q*dt**3/3,B=s.P[1]+dt*s.P[3]+q*dt*dt/2,D=s.P[3]+q*dt,S=A+R,k0=A/S,k1=B/S,e=z-xp,u=1-k0;return {x:[xp+k0*e,vp+k1*e],P:[u*u*A+k0*k0*R,u*(B-k1*A)+k0*k1*R,u*(B-k1*A)+k0*k1*R,D-2*k1*B+k1*k1*A+k1*k1*R],K:[k0,k1]};}
function tracking(sigma,q,R=sigma*sigma){const dt=.05;let seed=7,s=null;function rnd(){seed=(1664525*seed+1013904223)>>>0;return (seed+.5)/4294967296;}return Array.from({length:201},(_,n)=>{const t=n*dt,p=100+4*Math.max(0,Math.min(4,t-2)),v=t>=2&&t<6?4:0,z=p+sigma*Math.sqrt(-2*Math.log(rnd()))*Math.cos(2*Math.PI*rnd());s=s?kalmanStep(s,z,dt,q,R):{x:[z,0],P:[R,0,0,25],K:[0,0]};return {t,p,v,z,estimate:s.x[0],rate:s.x[1],P:s.P.slice()};});}
if(typeof module!=='undefined')module.exports={firDesign,butterDesign,magnitude,kalmanStep,tracking};
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id);
function plot(id,xmax,ymin,ymax,lines){const el=$(id),w=el.clientWidth,ht=el.clientHeight,dpr=window.devicePixelRatio||1;el.width=Math.round(w*dpr);el.height=Math.round(ht*dpr);const c=el.getContext('2d');c.scale(dpr,dpr);const L=48,R=14,T=15,B=32,x=t=>L+t/xmax*(w-L-R),y=v=>T+(ymax-v)/(ymax-ymin)*(ht-T-B);c.font='12px system-ui';c.fillStyle='#a2b6c9';c.lineWidth=1;for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4;c.strokeStyle='#253548';c.beginPath();c.moveTo(L,y(v));c.lineTo(w-R,y(v));c.stroke();c.fillText(v.toFixed(1),2,y(v)+4);c.fillText((xmax*i/4).toFixed(1),x(xmax*i/4)-8,ht-9);}c.save();c.beginPath();c.rect(L,T,w-L-R,ht-T-B);c.clip();for(const line of lines){c.strokeStyle=line.color;c.lineWidth=line.width||2;c.beginPath();line.data.forEach(([t,v],i)=>i?c.lineTo(x(t),y(v)):c.moveTo(x(t),y(v)));c.stroke();}c.restore();}
function updateFilters(){const M=+$('taps').value,fc=+$('firfc').value,N=+$('order').value,ifc=+$('iirfc').value,b=firDesign(M,fc,100),sos=butterDesign(N,ifc,100);$('firout').textContent=fc.toFixed(1)+' Hz';$('iirout').textContent=ifc.toFixed(1)+' Hz';$('firdetail').textContent=`${M} 个系数，${M-1} 阶；线性相位群延迟 ${(M-1)/2} 点 = ${((M-1)/200).toFixed(2)} 秒；直接实现每个输出约 ${M} 次乘法。`;const data=Array.from({length:501},(_,i)=>[i/10,magnitude(b,[1],i/10,100)]);plot('firplot',50,0,1.1,[{data,color:'#71d6ac'}]);$('fircoeff').textContent='b = [\n'+b.map(v=>v.toFixed(7)).join(', ')+'\n]';$('firgain').textContent=[1,10,30].map(f=>`${f} Hz 保留 ${(100*magnitude(b,[1],f,100)).toFixed(2)}%`).join(' · ');plot('iirplot',50,0,1.1,[{data:Array.from({length:501},(_,i)=>[i/10,sos.reduce((v,s)=>v*magnitude(s.b,s.a,i/10,100),1)]),color:'#c09aee'}]);$('iirdetail').textContent=`${N} 阶 = ${N/2} 个二阶节串联；每节有 b₀、b₁、b₂、a₁、a₂ 五个系数（a₀ 归一化为 1）。截止点保留约 70.7%。`; $('iircoeff').textContent=sos.map((s,i)=>`第 ${i+1} 节 Q值 = ${s.Q.toFixed(6)}\nb = [${s.b.map(v=>v.toFixed(7)).join(', ')}]\na = [${s.a.map(v=>v.toFixed(7)).join(', ')}]`).join('\n\n');}
function updateKalman(){const sigma=+$('measure').value,q=+$('process').value,R=+$('assumed').value,rows=tracking(sigma,q,R);$('measureout').textContent=sigma.toFixed(1)+' kPa';$('assumedout').textContent=R.toFixed(2)+' kPa²';$('processout').textContent=q.toFixed(2)+' kPa²/s³';const pressures=rows.flatMap(r=>[r.p,r.z,r.estimate]),rates=rows.flatMap(r=>[r.v,r.rate]);plot('pressureplot',10,Math.floor(Math.min(...pressures)-1),Math.ceil(Math.max(...pressures)+1),[{data:rows.map(r=>[r.t,r.z]),color:'#8198b0',width:1},{data:rows.map(r=>[r.t,r.p]),color:'#d5e1ec'},{data:rows.map(r=>[r.t,r.estimate]),color:'#6bd7e5'}]);plot('rateplot',10,Math.floor(Math.min(...rates)-.5),Math.ceil(Math.max(...rates)+.5),[{data:rows.map(r=>[r.t,r.v]),color:'#d5e1ec'},{data:rows.map(r=>[r.t,r.rate]),color:'#f1c57a'}]);const rmse=Math.sqrt(rows.reduce((s,r)=>s+(r.estimate-r.p)**2,0)/rows.length);$('kalmandetail').textContent=`实际噪声方差 σ² = ${(sigma*sigma).toFixed(2)} kPa²；算法假设 R = ${R.toFixed(2)} kPa²；压力估计 RMSE = ${rmse.toFixed(3)} kPa。首个压力读数初始化压力，初始变化率设为 0；P₀ = diag(R, 25)，第二项单位为 (kPa/s)²。噪声序列固定，便于调参比较。`;}
['taps','firfc','order','iirfc'].forEach(id=>$(id).addEventListener('input',updateFilters));['measure','process','assumed'].forEach(id=>$(id).addEventListener('input',updateKalman));window.addEventListener('resize',()=>{updateFilters();updateKalman();});updateFilters();updateKalman();
}
