'use strict';
function section(type,fc,fs){const k=Math.tan(Math.PI*fc/fs),r=(1-k)/(1+k),g=type==='low'?k/(1+k):1/(1+k);return {b:[g,type==='low'?g:-g],a:[1,-r]};}
function response(c,f,fs){const w=-2*Math.PI*f/fs,nr=c.b[0]+c.b[1]*Math.cos(w),ni=c.b[1]*Math.sin(w),dr=1+c.a[1]*Math.cos(w),di=c.a[1]*Math.sin(w),d=dr*dr+di*di;return {re:(nr*dr+ni*di)/d,im:(ni*dr-nr*di)/d};}
function cascade(a,b){return {re:a.re*b.re-a.im*b.im,im:a.re*b.im+a.im*b.re};}
function emaAlpha(fc,fs){const d=2*Math.sin(Math.PI*fc/fs)**2;return Math.sqrt(d*d+2*d)-d;}
if(typeof module!=='undefined')module.exports={section,response,cascade,emaAlpha};
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id),Fs=100,tones=[.5,5,20];let mode='low';
function h(f){const a=response(section(mode==='low'?'low':'high',+$('cutoff').value,Fs),f,Fs);return mode==='band'?cascade(a,response(section('low',+$('upper').value,Fs),f,Fs)):a;}
function canvas(id){const el=$(id),w=el.clientWidth,ht=el.clientHeight,dpr=window.devicePixelRatio||1;el.width=Math.round(w*dpr);el.height=Math.round(ht*dpr);const c=el.getContext('2d');c.scale(dpr,dpr);return {c,w,ht};}
function plot(id,xmax,ymin,ymax,series){const {c,w,ht}=canvas(id),L=42,R=15,T=15,B=32,x=t=>L+t/xmax*(w-L-R),y=v=>T+(ymax-v)/(ymax-ymin)*(ht-T-B);c.font='12px system-ui';c.fillStyle='#a2b6c9';c.strokeStyle='#253548';c.lineWidth=1;for(let i=0;i<=4;i++){let v=ymin+(ymax-ymin)*i/4;c.beginPath();c.moveTo(L,y(v));c.lineTo(w-R,y(v));c.stroke();c.fillText(v.toFixed(1),3,y(v)+4);let t=xmax*i/4;c.fillText(t.toFixed(1),x(t)-8,ht-9);}for(const s of series){c.strokeStyle=s.color;c.lineWidth=s.color==='#6bd7e5'?2.3:1.3;c.beginPath();s.data.forEach(([t,v],i)=>i?c.lineTo(x(t),y(v)):c.moveTo(x(t),y(v)));c.stroke();}if(!series.length)c.fillText('勾选上方开关，显示曲线',L+10,ht/2);}
function update(){let fc=+$('cutoff').value,upper=+$('upper').value;if(mode==='band'&&upper<=fc){upper=Math.min(49,fc+.1);$('upper').value=upper;}$('cutout').textContent=fc.toFixed(1)+' Hz';$('upperout').textContent=upper.toFixed(1)+' Hz';$('uppercontrol').hidden=mode!=='band';$('cutlabel').textContent=mode==='band'?'高通段截止频率':'截止频率';$('meaning').textContent={low:'低通：慢变化比较容易留下，快变化受到削弱。先试着拖动截止频率。',high:'高通：减轻缓慢漂移，保留更多快速变化。绝对压力的基线会被去掉。',band:'带通：先经高通，再经低通。拖动两个边界，观察中间的 5 Hz 成分。'}[mode];$('cutnote').textContent=mode==='band'?'两个滑块控制各自一段的截止频率。低通段必须高于高通段；必要时会自动上调。整个带通的峰值没有归一化。':'截止处幅度约剩 70.7%，并非完全消失。改变截止频率也会改变相位，也就是各成分在时间上的对齐位置。';
const hs=tones.map(h);$('components').innerHTML=tones.map((f,i)=>{const a=Math.hypot(hs[i].re,hs[i].im);return `<div class="component"><div>${f} Hz · ${['慢变化','中速振动','快速抖动'][i]}<small>输入 1 → 输出 ${a.toFixed(3)} kPa</small></div><strong>${(100*a).toFixed(1)}%</strong><div class="track"><span style="width:${100*a}%"></span></div></div>`;}).join('');const input=[],output=[];for(let n=0;n<=400;n++){let t=n/Fs;input.push([t,tones.reduce((s,f)=>s+Math.sin(2*Math.PI*f*t),0)]);output.push([t,tones.reduce((s,f,i)=>s+hs[i].re*Math.sin(2*Math.PI*f*t)+hs[i].im*Math.cos(2*Math.PI*f*t),0)]);}plot('timeplot',4,-3.2,3.2,[$('showinput').checked?{data:input,color:'#899eb5'}:null,$('showoutput').checked?{data:output,color:'#6bd7e5'}:null].filter(Boolean));const gain=[];for(let i=0;i<=1000;i++){const f=i*50/1000,v=h(f);gain.push([f,Math.hypot(v.re,v.im)]);}plot('gainplot',50,0,1,[{data:gain,color:'#6bd7e5'}]);const cs=[section(mode==='low'?'low':'high',fc,Fs)];if(mode==='band')cs.push(section('low',upper,Fs));$('coefficients').textContent=cs.map((c,i)=>`${mode==='band'?(i===0?'高通段':'低通段'):'当前段'}：\ny[n] = ${(-c.a[1]).toFixed(6)} × y[n−1] + ${c.b[0].toFixed(6)} × x[n] ${c.b[1]<0?'−':'+'} ${Math.abs(c.b[1]).toFixed(6)} × x[n−1]`).join('\n\n');$('emaexample').textContent=`例如 Fs = 100 Hz、fc = ${fc.toFixed(1)} Hz 时，α = ${emaAlpha(fc,Fs).toFixed(6)}。这个 α 对应指数平滑，不替代上面实验的 g、r。`;
}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$('cutoff').value=mode==='high'?10:2;$('upper').value=10;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));update();});['cutoff','upper','showinput','showoutput'].forEach(id=>$(id).addEventListener('input',update));document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{$('checkanswer').textContent=b.dataset.answer==='no'?'对。M 决定用了多少个样本，系数决定怎样组合它们。加法与减法就可能带来完全不同的频率选择。':'再比较上面两组系数：同样 2 个样本，求和保留恒定值，求差会去掉恒定值。窗口长度还不够描述滤波效果。';});window.addEventListener('resize',update);update();
}
