'use strict';
const el=id=>document.getElementById(id);
function plot(id,series,{xmin=0,xmax=1,ymin=-5,ymax=5,xlabel='时间 / s',ylabel='信号',dots=false,mark=null}={}){const c=el(id),rect=c.getBoundingClientRect();if(!rect.width)return;const d=window.devicePixelRatio||1;c.width=rect.width*d;c.height=rect.height*d;const ctx=c.getContext('2d');ctx.scale(d,d);const w=rect.width,h=rect.height,L=44,R=16,T=25,B=42;const px=v=>L+(v-xmin)/(xmax-xmin)*(w-L-R),py=v=>h-B-(v-ymin)/(ymax-ymin)*(h-T-B);ctx.font='12px system-ui';for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4,y=py(v);ctx.strokeStyle='#d7e3ef';ctx.beginPath();ctx.moveTo(L,y);ctx.lineTo(w-R,y);ctx.stroke();ctx.fillStyle='#596f88';ctx.textAlign='right';ctx.fillText(Number(v.toFixed(2)),L-6,y+4);const t=xmin+(xmax-xmin)*i/4;ctx.textAlign='center';ctx.fillText(Number(t.toFixed(2)),px(t),h-23);}ctx.textAlign='left';ctx.fillText(ylabel,L,14);ctx.textAlign='right';ctx.fillText(xlabel,w-R,h-4);series.forEach(s=>{ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineWidth=2;ctx.setLineDash(s.dash?[5,4]:[]);ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(px(p[0]),py(p[1])):ctx.moveTo(px(p[0]),py(p[1])));ctx.stroke();if(dots&&!s.dash)s.points.forEach(p=>{ctx.beginPath();ctx.arc(px(p[0]),py(p[1]),3,0,2*Math.PI);ctx.fill();});});ctx.setLineDash([]);if(mark){ctx.fillStyle='#a76513';ctx.beginPath();ctx.arc(px(mark[0]),py(mark[1]),5,0,2*Math.PI);ctx.fill();}}
function complex(re,im){if(Math.abs(re)<1e-8)re=0;if(Math.abs(im)<1e-8)im=0;if(!im)return re.toFixed(2);if(!re)return im.toFixed(2)+'j';return re.toFixed(2)+(im>=0?' + ':' − ')+Math.abs(im).toFixed(2)+'j';}
function fourier(){const a=Number(el('amplitude').value),deg=Number(el('phase').value),ph=deg*Math.PI/180;el('aout').textContent=a.toFixed(1);el('phout').textContent=deg+'°';el('fexpression').textContent=`x(t) = ${a.toFixed(1)} cos(2π × 3t + ${deg}°)`;el('cplus').textContent=complex(a/2*Math.cos(ph),a/2*Math.sin(ph));el('cminus').textContent=complex(a/2*Math.cos(ph),-a/2*Math.sin(ph));el('fmeaning').textContent=a===0?'信号为零，两个系数也都是零。此时相位没有可辨认的意义。':`余弦振幅是 ${a.toFixed(1)}；每个复数系数的模长（复数在平面上的长度）是 ${(a/2).toFixed(1)}。${deg===180?'系数是负实数，表示相位翻转，而不是振幅变成负数。':deg===0?'两个系数都是正实数，两个旋转在初始时刻指向同一方向。':'相位改变会改变系数的实部和虚部，但模长仍由振幅决定。'}`;plot('fwave',[{color:'#165ba7',points:Array.from({length:501},(_,i)=>[i/500,a*Math.cos(2*Math.PI*3*i/500+ph)])}],{ymin:-8,ymax:8,ylabel:'相对信号值'});}
function laplace(){const tau=Number(el('tau').value);el('tauout').textContent=tau.toFixed(1);el('lmeaning').textContent=`蓝线是输出，虚线是 1 V 输入。经过 ${tau.toFixed(1)} 秒（一个 τ），输出约为 0.632 V；经过 ${(5*tau).toFixed(1)} 秒，约为 0.993 V。对应极点为 s = ${(-1/tau).toFixed(2)} /秒。`;plot('lwave',[{color:'#aa7c35',dash:true,points:[[0,1],[10,1]]},{color:'#165ba7',points:Array.from({length:501},(_,i)=>[i/50,1-Math.exp(-i/50/tau)])}],{xmax:10,ymin:0,ymax:1.1,ylabel:'电压 / V',mark:[tau,1-Math.exp(-1)]});}
function zlesson(){const a=Number(el('alphaZ').value);el('azout').textContent=a.toFixed(2);let y=0;const points=Array.from({length:31},(_,n)=>{y+=a*(1-y);return[n,y];});el('zmeaning').textContent=`第一点 y[0] = ${a.toFixed(2)}。${a===1?'α = 1 时输入直接传到输出，不再有平滑作用。':`每一步保留上次输出的 ${(1-a).toFixed(2)}，极点在 z = ${(1-a).toFixed(2)}。α 越小，达到目标所需的采样次数越多。`}图中的点是实际采样输出，连线只帮助观察。`;plot('zwave',[{color:'#aa7c35',dash:true,points:[[0,1],[30,1]]},{color:'#165ba7',points}],{xmax:30,ymin:0,ymax:1.1,xlabel:'采样编号 n',ylabel:'归一化输出',dots:true});}
function redraw(){fourier();laplace();zlesson();}
function tab(id,scroll=false){document.querySelectorAll('[role=tabpanel]').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.tab===id));b.tabIndex=b.dataset.tab===id?0:-1;});redraw();if(scroll)document.querySelector('main > nav[role=tablist]').scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('[data-tab]').forEach((b,i,all)=>{b.onclick=()=>tab(b.dataset.tab);b.onkeydown=e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%all.length;else if(e.key==='ArrowLeft')n=(i+all.length-1)%all.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=all.length-1;else return;e.preventDefault();all[n].focus();tab(all[n].dataset.tab);};});document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>tab(b.dataset.next,true));['amplitude','phase'].forEach(id=>el(id).oninput=fourier);el('tau').oninput=laplace;el('alphaZ').oninput=zlesson;document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const ok=b.dataset.ok==='true',id=b.dataset.check;el('check-'+id).textContent=ok?({f:'对，振幅表示大小，仍为 4；负实系数在这个例子里对应 180° 的相位反转。',l:'对，τ 变大，充电和趋近目标的过程更慢；稳定后的增益仍为 1。',z:'对，这里的 z⁻¹ 对应一拍延迟；它不是压力读数的倒数。'}[id]):'再想一下：看看上面的图、符号解释，或者动手调一次参数。';});window.addEventListener('resize',redraw);tab('fourier');
